import * as crypto from 'crypto';
import type { WebClient } from '@slack/web-api';
import { getGithubRepo, getWorkspaceId } from 'services/slack';
import { GitHubSyncService } from 'services/sync/github-sync-service';
import { WorkspaceStore } from 'services/workspace/workspace-store';
import { CHOIRMessageType, createCHOIRBlockId } from 'types/message-types';

/**
 * GitHub webhook 서명을 검증하는 함수
 */
export function verifyGitHubSignature(payload: string, signature: string, secret: string): boolean {
  if (!signature || !secret) {
    return false;
  }

  const expectedSignature = crypto
    .createHmac('sha256', secret)
    .update(payload, 'utf8')
    .digest('hex');

  const expectedSignatureWithPrefix = `sha256=${expectedSignature}`;

  // timing attack을 방지하기 위해 crypto.timingSafeEqual 사용
  return crypto.timingSafeEqual(
    Buffer.from(signature, 'utf8'),
    Buffer.from(expectedSignatureWithPrefix, 'utf8')
  );
}

/**
 * 현재 워크스페이스가 해당 저장소와 매칭되는지 확인
 */
export async function isRepoMatchingWorkspace(owner: string, repo: string, client: WebClient): Promise<boolean> {
  try {
    const workspaceId = await getWorkspaceId(client);
    const repoInfo = await getGithubRepo(workspaceId);
    
    return repoInfo?.owner === owner && repoInfo?.repo === repo;
  } catch (error) {
    console.error('Error checking repo matching:', error);
    return false;
  }
}

/**
 * 커밋이 CHOIR에서 자동 생성된 것인지 확인
 */
export function isChoirGeneratedCommit(commits: any[]): boolean {
  if (!commits || commits.length === 0) {
    return false;
  }

  // 모든 커밋 메시지에 [choir-auto] 마커가 있는지 확인
  return commits.every(commit => 
    commit.message && commit.message.includes('[choir-auto]')
  );
}

/**
 * GitHub push 이벤트를 처리하는 함수
 */
export async function handleGitHubPushEvent(
  payload: any,
  client: WebClient,
  logger: any
): Promise<void> {
  try {
    const { repository, ref, commits } = payload;
    const owner = repository.owner.name || repository.owner.login;
    const repo = repository.name;
    const branch = ref.replace('refs/heads/', '');
    const defaultBranch = repository.default_branch;

    logger.info(`GitHub push event received: ${owner}/${repo} on branch ${branch}`);
    logger.info(`Commits: ${commits?.length || 0}`);

    // 현재 워크스페이스가 해당 저장소를 사용하는지 확인
    const isMatching = await isRepoMatchingWorkspace(owner, repo, client);
    
    if (!isMatching) {
      logger.info(`Repository ${owner}/${repo} does not match current workspace`);
      return;
    }

    // CHOIR에서 자동 생성한 커밋인지 확인
    if (isChoirGeneratedCommit(commits)) {
      logger.info(`Skipping auto-reload: commits are generated by CHOIR itself`);
      return;
    }

    logger.info(`Repository ${owner}/${repo} matches current workspace, performing auto-reload`);

    // 자동 reload 수행
    await performAutoReloadForWorkspace(owner, repo, branch, commits, client, logger, defaultBranch);
  } catch (error) {
    logger.error('Error handling GitHub push event:', error);
  }
}

/**
 * 현재 워크스페이스에 대해 자동 reload 수행
 */
async function performAutoReloadForWorkspace(
  owner: string,
  repo: string,
  branch: string,
  commits: any[],
  client: WebClient,
  logger: any,
  defaultBranch?: string
): Promise<void> {
  try {
    const workspaceId = await getWorkspaceId(client);
    const repoInfo = await getGithubRepo(workspaceId);
    
    if (!repoInfo) {
      logger.warn('No GitHub repository configured for current workspace');
      return;
    }

    // 브랜치가 다르면 스킵 (기본 브랜치만 처리)
    const configBranch = repoInfo.branch || defaultBranch || 'main';
    if (branch !== configBranch) {
      logger.info(`Skipping auto-reload: branch ${branch} != ${configBranch}`);
      return;
    }

    logger.info('Performing auto-reload for current workspace');

    // 워크스페이스의 관리자들 가져오기
    const workspaceStore = new WorkspaceStore();
    const workspaceConfig = await workspaceStore.getWorkspaceConfig(workspaceId);
    const managers = workspaceConfig?.managers || [];
    
    if (managers.length === 0) {
      logger.warn('No managers found for current workspace');
      return;
    }

    // 모든 관리자에게 진행 상황 메시지 전송
    for (const managerId of managers) {
      await client.chat.postMessage({
        channel: managerId,
        text: `🔄 Reflecting your document changes...`,
        blocks: [
          {
            type: 'section',
            text: {
              type: 'mrkdwn',
              text: `🔄 Reflecting your document changes...`,
            },
            block_id: createCHOIRBlockId(CHOIRMessageType.STATUS_UPDATE),
          },
        ],
      });
    }

    // 첫 번째 관리자를 대신해서 reload 수행
    const firstManager = managers[0];

    // VectorStoreService를 직접 사용해서 reload 수행
    const { VectorStoreService } = await import('services/vector/main-service');
    const { GithubService } = await import('services/github');
    
    const githubService = GithubService.getInstance();
    const gitHubSyncService = GitHubSyncService.getInstance();
    const vectorStore = VectorStoreService.getInstance();

    // GitHub에서 최신 파일들 가져오기
    const markdownFiles = await githubService.getAllMarkdownFiles({
      owner,
      repo,
      path: repoInfo.path || '',
      ref: branch,
      workspaceId,
      userId: firstManager,
    });

    if (markdownFiles.length === 0) {
      // 모든 관리자에게 실패 메시지 전송
      for (const managerId of managers) {
        await client.chat.postMessage({
          channel: managerId,
          text: '❌ Unable to reflect changes: No documents found.',
          blocks: [
            {
              type: 'section',
              text: {
                type: 'mrkdwn',
                text: `❌ Unable to reflect changes: No documents found. <https://github.com/${owner}/${repo}|View Repository>`,
              },
              block_id: createCHOIRBlockId(CHOIRMessageType.RESPONSE),
            },
          ],
        });
      }
      return;
    }

    // 벡터 저장소 업데이트
    const success = await vectorStore.initialize(markdownFiles, false, true, workspaceId);

    if (success) {
      const latestCommit = commits && commits.length > 0 ? commits[commits.length - 1] : null;

      // 캐시 업데이트
      const fileList = markdownFiles.map((file) => ({
        name: file.name,
        path: file.path,
      }));
      await workspaceStore.setMarkdownFilesCache(workspaceId, fileList);
      await gitHubSyncService.syncWorkspaceFromMarkdownFiles({
        workspaceId,
        owner,
        repo,
        branch,
        markdownFiles,
        source: 'webhook',
        commitSha: latestCommit?.id,
      });

      // 가장 최근 commit의 URL 생성 (가장 마지막 commit 사용)
      const commitUrl = latestCommit 
        ? `https://github.com/${owner}/${repo}/commit/${latestCommit.id}`
        : `https://github.com/${owner}/${repo}`;
      const linkText = latestCommit ? 'View Changes' : 'View Repository';

      // 모든 관리자에게 성공 메시지 전송
      for (const managerId of managers) {
        await client.chat.postMessage({
          channel: managerId,
          text: `✅ Document changes reflected successfully! Updated ${markdownFiles.length} files. ${linkText}`,
          blocks: [
            {
              type: 'section',
              text: {
                type: 'mrkdwn',
                text: `✅ Document changes reflected successfully! Updated ${markdownFiles.length} files. <${commitUrl}|${linkText}>`,
              },
              block_id: createCHOIRBlockId(CHOIRMessageType.SUCCESS),
            },
          ],
        });
      }

      logger.info(`Auto-reload completed: ${markdownFiles.length} files`);
    } else {
      // 모든 관리자에게 실패 메시지 전송
      for (const managerId of managers) {
        await client.chat.postMessage({
          channel: managerId,
          text: '❌ Unable to reflect changes: Processing failed.',
          blocks: [
            {
              type: 'section',
              text: {
                type: 'mrkdwn',
                text: `❌ Unable to reflect changes: Processing failed. Try "Reload From Github" in Home or contact research team. <https://github.com/${owner}/${repo}|View Repository>`,
              },
              block_id: createCHOIRBlockId(CHOIRMessageType.RESPONSE),
            },
          ],
        });
      }
      logger.error('Auto-reload failed: vector store update failed');
    }
  } catch (error) {
    logger.error('Error in performAutoReloadForWorkspace:', error);
    
    // 오류 알림
    try {
      const workspaceId = await getWorkspaceId(client);
      const workspaceStore = new WorkspaceStore();
      const workspaceConfig = await workspaceStore.getWorkspaceConfig(workspaceId);
      const managers = workspaceConfig?.managers || [];
      
      if (managers.length > 0) {
        // 모든 관리자에게 에러 알림 전송
        for (const managerId of managers) {
          await client.chat.postMessage({
            channel: managerId,
            text: `❌ Unable to reflect document changes: System error occurred.`,
            blocks: [
              {
                type: 'section',
                text: {
                  type: 'mrkdwn',
                  text: `❌ Unable to reflect document changes: System error occurred. Try "Reload From Github" in Home or contact research team. <https://github.com/${owner}/${repo}|View Repository>`,
                },
                block_id: createCHOIRBlockId(CHOIRMessageType.RESPONSE),
              },
            ],
          });
        }
      }
    } catch (notificationError) {
      logger.error('Failed to send error notification:', notificationError);
    }
  }
}
